version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: tmh
    volumes:
      - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@tmh
      - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test:  rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 5s
      retries: 5